upstream django {
    server python:8000; # for a web port socket (we'll use this first)
}

server {
    listen 80;
    server_name gis.example.org;
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name gis.example.org;

    ssl_certificate /etc/letsencrypt/live/gis.example.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gis.example.org/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    charset     utf-8;
    access_log  /var/log/nginx/host.access.log  main;

    location / {
        uwsgi_pass  django;
        include /etc/nginx/uwsgi_params;
    }
}
